import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sweet Dreams",
  description: "Generated by create next app",

  keywords: [
    "sweet dreams",
    "mamaw",
    "cakery",
    "Asturias",
    "Sangi, Asturias",
    "Sangi",
    "Cakery",
    "Custom Cakes",
    "Custom Cupcakes",
    "Customized Cakes",
    "Marimar",
    "Tubigagmanok",
    "Cake Tubigan",
    "Tubigan",
    "Money Cake",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
